export const ButtonArr = [
    "useLocalStorage",
    "useDataAPI",
    "useLocation",
    "useNavigation",
    "useCache",
    "useCookies",
    "useDate",
    "useDiameter",
    "useDataAPI",
    "useLocalStorage",
    "useLocation",
    "useNavigation",
    "useCache",
    "useCookies",
    "useDateAPI",
    "useDiameter",
  ];
  
  export const ButtonArrTwo = [
    "",
    "useNavigation",
    "useDiameter",
    "useDataAPI",
    "useLocation",
    "useCache",
    "useCookies",
    "useLocalStorage",
    "useDate",
    "useNavigation",
    "useDiameter",
    "useDataAPI",
    "useLocation",
    "useCache",
    "useCookies",
    "useLocalStorage",
    "useDateAPI",
  ];