export const ButtonArr = [
  "",  
  "",  
    "useLocalStorage",
    "useDataAPI",
    "useLocation",
    "useRealTimeLocation",
    "useScript",
    "useLocalStorage",
    "useHasFocus",
    "useIdle",
    "useCurrentLocation",
    "usePrevious",
    "useScript",
    "useResponsive",
    "useScript",
    "useLocalStorage",
    "useHasFocus",
    "useIdle",
    "useCurrentLocation",
    "usePrevious",
    "useScript",
    "useResponsive",



  ];
  
  export const ButtonArrTwo = [
    "",
    "",
    "",
    "",
    "",
    "",  
    "",  
    "useCurrentLocation",
    "useDebounce",
    "useRealTimeLocation",
    "useLocalStorage",
    "useThrottle",
    "useDebounce",
    "useInfiniteScroll",
    "useCookies",
    "useCurrentLocation",
    "useDebounce",
    "useRealTimeLocation",
    "useLocalStorage",
    "useThrottle",
    "useDebounce",
    "useInfiniteScroll",
    "useCookies",

  ];