export const ButtonArr = [
  "",  
  "useLocalStorage",
    "useDataAPI",
    "useLocation",
    "useRealTimeLocation",
    "useDate",
    "useDataAPI",
    "useCurrentLocation",
    "useLocalStorage",
    "useCurrentLocation",
    "useCookies",
    "useLocalStorage",
    "useCurrentLocation",
  ];
  
  export const ButtonArrTwo = [
    "",
    "",
    "",
    "",
    "",
    "useNavigation",
    "useDiameter",
    "useCurrentLocation",
    "useDataAPI",
    "useRealTimeLocation",
    "useLocalStorage",
    "useDate",
    "useRealTimeLocation",
    "useDataAPI",
    "useCookies",
    "useLocalStorage",
    "useDateAPI",
  ];