export const ButtonArr = [
   "",  
   "",  
    "useLocalStorage",
    "useDataAPI",
    "useLocation",
    "useRealTimeLocation",
    "useScript",
    "useResponsive",
    "useHasFocus",
    "useScript",
    "useResponsive",
    "useCurrentLocation",
    "useHasFocus",
    "useIdle",
    "usePrevious",
    "useScript",
  ];
  
  export const ButtonArrTwo = [
    "useIdle",
    "useCurrentLocation",
    "useDebounce",
    "useRealTimeLocation",
    "useLocalStorage",
    "useInfiniteScroll",
    "useThrottle",
    "useDebounce",
    "useCookies",
    "useCurrentLocation",
    "useIdle",
    "useRealTimeLocation",
    "useThrottle",
    "useDebounce",
    "useInfiniteScroll",
    "useCookies",
  ];